### ISSUE TITLE
[RFC] Testcase for python-backports-ssl_match_hostname

### ISSUE THREAD

**Issue by athira-rajeev** [autotest/autotest-client-tests#49]
Testcase for python-backports-ssl_match_hostname

About the package:
Secure Socket Layer is secure when the hostname in the certificate returned
by the server matches to hostname thats being trying to be reached.
match_hostname() in ssl package in the Standard Library of Python 3.2  performs this check
instead of requiring every application to implement the check separately.

backport brings ``match_hostname()`` to users of earlier versions of Python.

Approach for testing:
=============

1)
- Create a self signed SSL certificate using openssl
- Create a server socket:
            - create a socket and bind the socket to a port
- Now as client, connect to the server and get the server's certificate using getpeercert()
 getpeercert() returns the certificate in decoded format.
- Verify the cert matches the hostname using match_hostname from backports.ssl_match_hostname
        ex: match_hostname(ssl_sock.getpeercert(), "hostname")

Example usage:
>>> import socket, ssl, pprint
>>> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> ssl_sock = ssl.wrap_socket(s, ca_certs="server.crt", cert_reqs=ssl.CERT_REQUIRED)
>>> ssl_sock.connect(('localhost', 1002))
>>> from backports.ssl_match_hostname import match_hostname, CertificateError
>>> match_hostname(ssl_sock.getpeercert(), "hostname") 

2) check whether match_hostname gives mismatch for wrong hostname

>>> from backports.ssl_match_hostname import match_hostname, CertificateError
>>> cert = {'subject': ((('commonName', 'example.com'),),)}
>>> match_hostname(cert, "example.com")
>>> match_hostname(cert, "example.org")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/backports/ssl_match_hostname/__init__.py", line 99, in match_hostname
    % (hostname, dnsnames[0]))
backports.ssl_match_hostname.CertificateError: hostname 'example.org' doesn't match 'example.com'

**Comment by athira-rajeev** [comment]
This testcase will be added to linux-tools .
@lmr , did you get a chance to look at this.

**Comment by lmr** [comment]
Looks fine to me.

**Comment by sathnaga** [comment]
This looks fine to me, how about using wget as another test scenario, that would be more from a user level :-)

**Comment by athira-rajeev** [comment]
PR  #51 for this is merged. Closing this issue
