### ISSUE TITLE
[RFC] Testcase for avahi-autoipd

### ISSUE THREAD

**Issue by athira-rajeev** [autotest/autotest-client-tests#54]
avahi-autoipd - IPv4LL network address configuration daemon

avahi-autoipd implements IPv4LL, "Dynamic Configuration of IPv4 Link-Local Addresses" (IETF RFC3927), a protocol for automatic IP address configuration from the link-local 169.254.0.0/16 range 
without the need for a central server. It is primarily intended to be used in ad-hoc networks which lack a DHCP server 

The package provides avahi-autoipd binary

Approach for testing
====================

Setup:

- Create virtual interface using ip command .

       #ip link add veth0 type veth peer name veth1

This creates interface veth0 and veth1 

Testing avahi-autoipd:
—————————-

1) Start avahi-autoipd on veth0

Example:
     
     #avahi-autoipd veth0
     Found user 'avahi-autoipd' (UID 170) and group 'avahi-autoipd' (GID 170).
     Successfully called chroot().
     Successfully dropped root privileges.
     Starting with address 169.254.8.223 
     Callout BIND, address 169.254.8.223 on interface veth0
     Successfully claimed IP address 169.254.8.223

Verify the results using ip command:

    #ip addr show veth0 |grep -w inet
    inet 169.254.8.223/16 brd 169.254.255.255 scope link veth0:avahi

Also try logging in with the ip and verify its working

2) option: -k     kill running avahi-autoipd
Kill the avahi-autoipd using -k
Ex:
 
     #avahi-autoipd -k veth0

and verify address is removed from interface veth0 using:
     #ip addr show veth0 |grep -w inet

3) option: -s      --syslog  ( Write log messages to syslog )

Start avahi-autoipd using -s:
     #avahi-autoipd -s veth0

and verify /var/log/messages is populated with the data

4) Testing switches —D, c, -r ( needs daemon to be running )

-D --daemonize      Daemonize after startup
-r --refresh        Request a running daemon refresh its IP address
-c --check          Return 0 if a daemon is already running

Start avahi-autoipd with -D option ( daemon mode )

    #avahi-autoipd -D veth0

Verify veth0 is assigned IP using ip command:
    #ip addr show veth0 |grep -w inet

Check if the daemon is already running using -c:

     #avahi-autoipd -c veth0
    -bash-4.2# echo $?
    0

Request daemon refresh IP address using -r:

Example:
   
    # avahi-autoipd -r veth0

Logs will have:
<<>>
Reannouncing address
Successfully claimed IP address 169.254.8.223
<<>>

5) -S address  Start with this address

start avahi-autoipd using -S and address option 

Example:

    #avahi-autoipd -S 169.254.8.224 veth0
    Found user 'avahi-autoipd' (UID 170) and group 'avahi-autoipd' (GID 170).
    Successfully called chroot().
    Successfully dropped root privileges.
    Starting with address 169.254.8.224
    Callout BIND, address 169.254.8.224 on interface veth0
    Successfully claimed IP address 169.254.8.224

Verify this address is assigned using ip command

     #ip addr show veth0|grep -w inet
    inet 169.254.8.224/16 brd 169.254.255.255 scope link veth0:avahi

6) --force-bind     Assign an IPv4LL address even if a routable address is assigned already

Assign a routable address to the interface :

          # ip addr add 192.168.122.2 dev veth0

Run avahi-autoipd which should not assign IP as already address is configured on the interface:
Example:

     #avahi-autoipd veth0
     Found user 'avahi-autoipd' (UID 170) and group 'avahi-autoipd' (GID 170).
     Successfully called chroot().
     Successfully dropped root privileges.
     Starting with address 169.254.8.224
     Routable address already assigned, sleeping.

Now using —force-bind:

     #avahi-autoipd --force-bind veth0
     Found user 'avahi-autoipd' (UID 170) and group 'avahi-autoipd' (GID 170).
    Successfully called chroot().
    Successfully dropped root privileges.
    Starting with address 169.254.8.224
    Callout BIND, address 169.254.8.224 on interface veth0
    Successfully claimed IP address 169.254.8.224

—force-bind will assign the IP.
Verify using ip command:

    #ip addr show veth0|grep -w inet
    inet 169.254.8.224/16 brd 169.254.255.255 scope link veth0:avahi
    inet 192.168.122.2/32 scope global veth0

**Comment by lmr** [comment]
OK!
