### ISSUE TITLE
[RFC]Testcase for Time command

### ISSUE THREAD

**Issue by basheerk** [autotest/autotest-client-tests#57]
**time** - time is a simple command,it gives resource usage.

The  time utility runs the specified program/command with the given arguments.  When program/command finishes, time writes a message to standard error giving timing statistics about the program/command run. These statistics consist of 
	(i)   The elapsed real time between invocation and termination, 
	(ii)  The user CPU time , and 
	(iii) The system CPU time .

**Binaries Provided** - /usr/bin/time

**Approach For Testing**:

1. Installation check for time rpm

2.To verify output format of time command with -p or --portability option
   Example:

	# /usr/bin/time -p sleep 2
	real 2.00
	user 0.00
	sys 0.00

3.To verify the Exit Status of the command using the Time utility.
	(i) If command is Invoked using time, the exit status is that of command invoked,otherwise it is 127 if command could not be found.

   Example:

	# /usr/bin/time -f "%x Exit status for %C" pwd
	/home/basheer/
	0 Exit status for pwd

	# /usr/bin/time -f "%x Exit status for %C" pwd1
	/usr/bin/time: cannot run pwd1: No such file or directory
	127 Exit status for pwd1

4.To verify output file is created or not, using --output or -o option.

   Example:

	# /usr/bin/time -o time_out.txt sleep 2
	The above statement should create a time_out.txt file

5.To verify the -append or -a option provided by time utility

   Example:

	# /usr/bin/time -v -a -o time_out.txt sleep 3
	The output of the "sleep 3" command should be appended to time_out.txt

6.To verify the --format or -f option and verify the output pattren as provided.
	
   Example:

	# /usr/bin/time -f "%E real,%U user,%S sys,'%C' cmd-executed" sleep 2
	0:02.00 real,0.00 user,0.00 sys,'sleep 2' cmd-executed

7.Create custom shell script dynamically and provide the same as input to the time utility and verify the output.

	# /usr/bin/time <Shell-script>

   Example:

	# /usr/bin/time -v -o out ./custom-script.sh
	# cat out | grep custom-script1.sh
	Command being timed: "./custom-script.sh"

**Comment by athira-rajeev** [comment]
Patch for this testcase is merged. Closing the issue
