### ISSUE TITLE
[RFC] Test case for libndp 

### ISSUE THREAD

**Issue by ramyabs** [autotest/autotest-client-tests#58]
Testcase for  libndp
libndp -Library for Neighbor Discovery Protocol

Neighbor Discovery Protocol (NDP) is a part of the Internet Protocol suite used with IPv6.
NDP Protocol make use of ICMPv6 messages and solicited-node multicast addresses for operating its core function, which is tracking and discovering other IPv6 hosts that are present on the other side of connected interfaces. Another use of NDP is address autoconfiguration.

IPv6 nodes on the same link use Neighbor Discovery protocol to discover each others presence, to determine each others link-layer addresses, to find routers, and to maintain reachability information
about the paths to active neighbors.

NDP defines five ICMPv6  packet type for the purpose of router solicitation, router advertisement, neighbor solicitation, neighbor advertisement, and network redirects

libndp  package provides  one library and one binary,
libndp.so :which provides a wrapper for IPv6 Neighbor Discovery Protocol and
ndptool :tool for sending and receiving NDP messages.

Approach for testing:
=====================
1.  Check if libndp package is installed.

2.  Installation check for utilities ip ,route and tcpdump.

3.  Get active interface of the machine and assign to iface=eth0 .

    -bash-4.2# ip -6 route show default
     default via fe80::4e96:14ff:fe59:d7f0 dev eth0  proto ra  metric 1024  expires 1787sec

4.  Get the ipv6 address of system and extract  link local address to variable ns_verify=fe80::e61f:13ff:feb4:fcb0.

     -bash-4.2# ip addr show dev eth0 | sed -e's/^.*inet6 \([^ ]*\)\/.*$/\1/;t;d' |grep fe80*
     fe80::e61f:13ff:feb4:fcb0

5.  Start the tcpdump with filter icmp6  to capture only ICMPv6 packet types.

     -bash-4.2# tcpdump -n -i eth0 icmp6 

6.  Monitor incoming NDP messages on specified interface i.e iface=eth0 using "ndptool monitor -i eth0"

    -bash-4.2# ndptool monitor -i eth0  

7.  Send NDP message of  type neighbor Solicitation (NS) messages using  ndptool send -t ns -i eth0 and monitor it using "ndptool monitor -i eth0".
    Neighbor Solicitation: Neighbor solicitations are used by nodes to determine the link layer 
    address of a neighbor, or to verify that a neighbor is still reachable via a cached link layer address.
  
   -bash-4.2# ndptool send -t ns -i eth0 
   -bash-4.2# ndptool monitor -i eth0
    NDP payload len 24, from addr: fe80::e61f:13ff:feb4:fcb0, iface: eth0
    Type: NS
    Verify if neighbor Solicitation messages is been received in "ndptool monitor -i eth0" as-well as in tcpdump output.

8.  Now stop the tcpdump and ndptool monitor process .

9.  Start "ndptool monitor" to monitor incoming NDP messages of type  NS  by using "ndptool monitor -i eth0 -t ns ".

    Now send the Router Solicitation  ad NS messages using  "ndptool send -t rs -i eth0" and "ndptool send -t ns -i eth0"
    
    Verify if the message received by "ndptool monitor -i eth0 -t ns " is only of type  NS and it does 
     not contain messages of RS type. 

10. Send NDP message of  type RS and monitor it .
    Stop "ndptool monitor" and start "ndptool monitor -i eth0".
    Now send the Router Solicitation messages using " ndptool send -t rs -i eth0".
    Verify if  the message received by " ndptool monitor -i eth0 "is of  type RS .

**Comment by athira-rajeev** [comment]
Patch for this testcase is merged. Closing the issue
